id = "ultraviolet-theme"
name = "ultraViolet"
version = "0.3.0"
schema_version = 1
authors = ["Gurvir Randhawa <gurvirrandhawa28@gmail.com>"]
description = "A violet-toned theme designed for quality & visual comfort"
repository = "https://github.com/Gurvirr/zed-ultraViolet"
